### ISSUE TITLE
Update study parameters

### ISSUE THREAD

**Issue by jbragg** [toomim/utility#3]
launch_study() in models/utiliscope/tasks.py currently updates the conditions of a study if launch_study() is called on an existing study with new conditions. It does not update the parameters if new parameters are given.

As a hack, I have it update parameters as well in my code, but I know it is risky in general to update parameters if HITs are open. It helps, though, in my workflow, which is:

1) launch a study with no HITs
2) launch HITs with specific Get parameters
3) possibly change conditions (e.g., bonus amount) / parameters (e.g., price) and return to 2)

Perhaps there are notions of a 'study'  (or assumptions made by other functions / tables) that are incompatible with this workflow.

**Comment by toomim** [comment]
Oh. You're not running an experimental study on turk.
You're using turk to get work done.
So yeah, the idea of a study doesn't quite fit this.

Thanks for diving into this!

The bonus amount can be changed any time -- it doesn't even need to be in the study. I wrote a function in __init__.py called "alter_price(new_price)" that does this. You can run it in a controller function. This can't change the default price of a hit though, obviously, because the hit has already been created at this point.

There's also no reason you need to run all these hits within a single study... you can have multiple studies running simultaneously. I haven't tested this much but I bet it works.

I suspect that in your situation, you don't actually need the "studies" infrastructure at all. Maybe you'd prefer an API that just launches each hit individually, with custom parameters each time?

There's also an alter_conditions(new_conditions) function like alter_price(), but I think I got scared because of what it would do to data analysis over studies... which isn't something you need, so maybe it would be useful for you.

When you say Get parameters, are you talking about the amazon HIT parameters, i.e. hit_params, e.g. "price" "description" "title" "num_assignments"?

I'm going to be offline for a day and a half starting tomorrow morning!

**Comment by jbragg** [comment]
Yes at the moment, I'm not running a formal experiment with varying prices. But I still have found the notion of a "study" useful for organizing batches of HITs with similar properties.

I am not interested in changing HIT rewards once they have been launched -- only in changing HIT rewards for batches of HITs. I guess it is a question of whether (1) to use the same study grouping and launch HITs with different params / rewards OR (2) to create a new study grouping each time I make an adjustment to the parameters that are passed to Amazon. I hacked the code so I could do (1) and quickly change the price without creating an entirely new "study," but if there is a convincing reason to switch to (2), I could do that. It would just create a lot of studies.

I think I have run multiple "studies" at once and encountered no problems.

The Get parameters I was talking about were the parameters unique to my HITs, like my "id" parameter -- not the ones passed to Amazon.

Talk to you when you're back!
